/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crudTabla;

import crudTabla.gui.formPrincipal;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        formPrincipal formPrincipal = new formPrincipal();
        formPrincipal.setVisible(true);
        formPrincipal.setLocationRelativeTo(null);
    }
}
